using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace _3DModels.Models
{
    public class ModelCoordinator
    {



        // The Id property represents the primary key and will be auto-generated by the database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Role { get; set; }
        public string Responsibilities { get; set; }
        public int? ExperienceYears { get; set; }
        public DateTime? JoinDate { get; set; }
        public decimal? Salary { get; set; }
    }

}

